export const cityMap = {
  臺北市: "Taipei",
  新北市: "NewTaipei",
  桃園市: "Taoyuan",
  臺中市: "Taichung",
  臺南市: "Tainan",
  高雄市: "Kaohsiung",
  基隆市: "Keelung",
  新竹市: "Hsinchu",
  新竹縣: "HsinchuCounty",
  苗栗縣: "MiaoliCounty",
  彰化縣: "ChanghuaCounty",
  南投縣: "NantouCounty",
  雲林縣: "YunlinCounty",
  嘉義縣: "ChiayiCounty",
  嘉義市: "Chiayi",
  屏東縣: "PingtungCounty",
  宜蘭縣: "YilanCounty",
  花蓮縣: "HualienCounty",
  臺東縣: "TaitungCounty",
  金門縣: "KinmenCounty",
  澎湖縣: "PenghuCounty",
  連江縣: "LienchiangCounty",
};

export const cityList = [
  { label: "臺北市", value: "Taipei", ID: "Taipei", isPopular: true },
  { label: "新北市", value: "NewTaipei", ID: "NewTaipei", isPopular: true },
  { label: "桃園市", value: "Taoyuan", ID: "Taoyuan" },
  { label: "臺中市", value: "Taichung", ID: "Taichung", isPopular: true },
  { label: "臺南市", value: "Tainan", ID: "Tainan", isPopular: true },
  { label: "高雄市", value: "Kaohsiung", ID: "Kaohsiung", isPopular: true },
  { label: "基隆市", value: "Keelung", ID: "Keelung" },
  { label: "新竹市", value: "Hsinchu", ID: "Hsinchu" },
  { label: "新竹縣", value: "HsinchuCounty", ID: "HsinchuCountry" },
  { label: "苗栗縣", value: "MiaoliCounty", ID: "MiaoliCounty" },
  { label: "彰化縣", value: "ChanghuaCounty", ID: "ChanghuaCounty" },
  {
    label: "南投縣",
    value: "NantouCounty",
    ID: "NantouCounty",
  },
  { label: "雲林縣", value: "YunlinCounty", ID: "YunlinCounty" },
  { label: "嘉義縣", value: "ChiayiCounty", ID: "ChiayiCounty" },
  { label: "嘉義市", value: "Chiayi", ID: "Chiayi" },
  { label: "屏東縣", value: "PingtungCounty", ID: "PintungCounty" },
  { label: "宜蘭縣", value: "YilanCounty", ID: "YilanCounty", isPopular: true },
  {
    label: "花蓮縣",
    value: "HualienCounty",
    ID: "HualienCounty",
    isPopular: true,
  },
  {
    label: "臺東縣",
    value: "TaitungCounty",
    ID: "TaitungCounty",
  },
  { label: "金門縣", value: "KinmenCounty", ID: "KinmenCounty" },
  {
    label: "澎湖縣",
    value: "PenghuCounty",
    ID: "PenghuCounty",
    isPopular: true,
  },
  { label: "連江縣", value: "LienchiangCounty", ID: "LienchiangCounty" },
];
